packages: []
catalogs:
  build:
    '@iconify-json/carbon': ^1.2.10
    '@unocss/transformer-directives': ^66.3.2
    '@vitejs/plugin-vue': ^6.0.0
    unocss: ^66.3.2
    unplugin: ^2.3.5
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.1
  dev:
    '@antfu/eslint-config': ^4.16.2
    '@unocss/eslint-plugin': ^66.3.2
    eslint: ^9.30.1
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vue-tsc: ^3.0.1
  frontend:
    '@google/genai': ^1.8.0
    '@vueuse/core': ^13.5.0
    '@vueuse/integrations': ^13.5.0
    idb-keyval: ^6.2.2
    vue: ^3.5.17
    vue-router: ^4.5.1
  test:
    '@vue/test-utils': ^2.4.6
    jsdom: ^26.1.0
    vitest: ^3.2.4
  types:
    '@types/node': ^22.16.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
